# Created by Jekyll Writer
title: 那年十七
author: fubail@qq.com
description: .
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
github_username: 17-years-old
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: ''
